---
apiVersion: v1
kind: Service
metadata:
  name: food-master
  namespace: my-demo
spec:
  selector:
     app: food-master
  ports:
   - port: 80
     targetPort: 80
  type: LoadBalancer
